# Generated by Django 5.1.6 on 2025-04-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_plss', '0002_todoitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
